# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-gbcontainer-jby

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: crjby.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9CC37623C5AC422D96F81D447A4D7CC2 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_233728CF280F4C93BC99595A1DBF8419 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: crjby.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9CC37623C5AC422D96F81D447A4D7CC2 }}/guestbook:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-gbcontainer-jby'
          slot-name: 'Production'
          images: 'crjby.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9CC37623C5AC422D96F81D447A4D7CC2 }}/guestbook:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3CA99FB3676F4E1787E2763ABED43135 }}